### ISSUE TITLE
Close/Open Keyboard on Vertical Pan Gesture

### ISSUE THREAD

**Issue by jjbeach** [EddyVerbruggen/cordova-plugin-native-keyboard#72]
Hey Eddy,

First off, thank you for creating such a valuable plugin. 

I'm using it in an Ionic 3 app, and would love to be able to dismiss the keyboard via a vertical pan gesture/swipe when a user's finger hits the top of the messenger bar, as well as have it open when dragging up the messenger from the bottom.

When digging through your underlying code, I came across line 186 in NKSLKTextViewContoller.m

`self.keyboardPanningEnabled = YES`

but doesn't seem to be working out of the box. Any suggestions for how I could accomplish said behavior?

**Comment by EddyVerbruggen** [comment]
Hi!

Good question.

The iOS implementation of this plugin relies heavily on [a third party component]() and they've been struggling with this issue ever since iOS 9 came out. They tried to implement it but failed, so I'm afraid it will not be possible. For details, see https://github.com/slackhq/SlackTextViewController/pull/355

**Comment by BorntraegerMarc** [comment]
@EddyVerbruggen I wanted to re-visit this topic 6 months later. Is Close/Open Keyboard on Vertical Pan Gesture still impossible?

**Comment by EddyVerbruggen** [comment]
AFAIK it is.
